# Generated by Django 5.2.8 on 2025-11-16 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profilephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_profile1', to='profiles.profile')),
                ('profile2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_profile2', to='profiles.profile')),
            ],
            options={
                'unique_together': {('profile1', 'profile2')},
            },
        ),
        migrations.CreateModel(
            name='swipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to='profiles.profile')),
                ('target_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swiped_by', to='profiles.profile')),
            ],
            options={
                'unique_together': {('profile', 'target_profile')},
            },
        ),
    ]
